---
proam-callback:
  handler: lambda_functions/proam/callback.handler
  description: callback to read groupme post
  environment:
    BOT_POSTS_TABLE_NAME:
      Ref: AllBotPosts
    BOT_ID: 1cb7428c18c516f719d909030e
    GROUPME_URL: 'https://api.groupme.com/v3/bots/post'
  events:
    - http:
        path: groupme/proam/callback
        method: post
  memorySize: 128
  timeout: 15
  role:
    Fn::GetAtt: [BotLambdaRole, Arn]
  layers:
    - {Ref: PythonRequirementsLambdaLayer}
  package:
    include:
      - lambda_functions/proam/callback.py
      - phrases/brian.txt