---
callback:
  handler: lambda_functions/basketball/callback.handler
  description: callback to read groupme post
  environment:
    BOT_POSTS_TABLE_NAME:
      Ref: AllBotPosts
    BOT_ID: ${opt:basketball-bot-id}
    GROUPME_URL: 'https://api.groupme.com/v3/bots/post'
  events:
    - http:
        path: groupme/basketball/callback
        method: post
  memorySize: 128
  timeout: 15
  role:
    Fn::GetAtt: [BotLambdaRole, Arn]
  layers:
    - {Ref: PythonRequirementsLambdaLayer}
  package:
    include:
      - lambda_functions/basketball/callback.py

proam-callback:
  handler: lambda_functions/proam/callback.handler
  description: callback to read groupme post
  environment:
    BOT_POSTS_TABLE_NAME:
      Ref: AllBotPosts
    BOT_ID: ${opt:proam-bot-id}
    GROUPME_URL: 'https://api.groupme.com/v3/bots/post'
  events:
    - http:
        path: groupme/proam/callback
        method: post
  memorySize: 128
  timeout: 15
  role:
    Fn::GetAtt: [BotLambdaRole, Arn]
  layers:
    - {Ref: PythonRequirementsLambdaLayer}
  package:
    include:
      - lambda_functions/proam/callback.py
      - phrases/proam.txt